# config/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ray-serve'
    static_configs:
      - targets: ['ray-head:8000']
  
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
